Repository emqx/emqx, pull requests merged in 2018-11, with the labels that each got.

#1872 Add acking mechamism for shared dispatch
  etc/emqx.conf
  priv/emqx.schema
  src/emqx_packet.erl
  src/emqx_session.erl
  src/emqx_shared_sub.erl
  src/emqx_sm.erl
  test/emqx_broker_SUITE.erl
  test/emqx_mock_client.erl
  test/emqx_session_SUITE.erl
  test/emqx_shared_sub_SUITE.erl
Labels: enhancement

#1998 Fix function_clause in del_direct_routes/1
  etc/emqx.conf
  src/emqx_router.erl
  test/emqx_router_SUITE.erl
Labels: BUG

#1996 Bump version to 3.0.0
  Makefile
  src/emqx.app.src
Labels: enhancement

#1995 Fix the 'route_batch_delete' config
  Makefile
  src/emqx.app.src
Labels: BUG

#1993 Add an elegant batch module
  Makefile
  src/emqx_batch.erl
  test/emqx_batch_SUITE.erl
Labels: enhancement

#2008 Fix the atom leaks in emqx_reason_codes module.
  src/emqx_reason_codes.erl
Labels: Enhancement

#2006 Optimize read/write concurrency of mnesia/ets tables
  src/emqx_banned.erl
  src/emqx_router.erl
  src/emqx_router_helper.erl
  src/emqx_sm_registry.erl
  src/emqx_trie.erl
Labels: Optimization

#2005 For git older than 1.8, there is no shallow clone support
  Makefile
Labels: BUG
