Repository emqx/emqx, pull requests merged in 2019-06, with the labels that each got.

#2597 Optimize metrics using counters and persistent_term
  src/emqx_broker.erl
  src/emqx_cm.erl
  src/emqx_connection.erl
  src/emqx_metrics.erl
  src/emqx_protocol.erl
  src/emqx_router_helper.erl
  src/emqx_session.erl
  src/emqx_shared_sub.erl
  src/emqx_sm.erl
  src/emqx_stats.erl
  src/emqx_sys.erl
  src/emqx_ws_connection.erl
  test/emqx_broker_SUITE.erl
  test/emqx_metrics_SUITE.erl
  test/emqx_stats_tests.erl
Labels: Optimization

#2607 Fix retain in will message
  src/emqx_protocol.erl
Labels: BUG

#2609 Fix acl deny action logic
  src/emqx_protocol.erl
Labels: BUG

#2611 Improve the emqx_connection, emqx_ws_connection and emqx_frame modules
  Makefile
  include/emqx_mqtt.hrl
  src/emqx_channel.erl
  src/emqx_client.erl
  src/emqx_frame.erl
  src/emqx_listeners.erl
  src/emqx_protocol.erl
  src/emqx_session.erl
  src/emqx_ws_channel.erl
  test/emqx_SUITE.erl
  test/emqx_alarm_handler_SUITE.erl
  test/emqx_channel_SUITE.erl
  test/emqx_frame_SUITE.erl
  test/emqx_protocol_SUITE.erl
  test/emqx_ws_channel_SUITE.erl
Labels: BUG, Enhancement

#2650 Fix the massages order when batch dispatching
  src/emqx_session.erl
Labels: BUG
