Repository emqx/emqx, pull requests merged in 2019-08, with the labels that each got.

#2745 Improve the channel modules and fix the extension mods
  src/emqx_channel.erl
  src/emqx_mod_presence.erl
  src/emqx_mod_subscription.erl
  src/emqx_protocol.erl
  src/emqx_ws_channel.erl
Labels: Enhancement

#2747 Specify mnesia dir for `make run` command
  test/run_emqx.escript
Labels: Enhancement

#2749 Move test/run_emqx.escript -> scripts/run_emqx.escript
  Makefile
  scripts/run_emqx.escript
Labels: Enhancement

#2766 Improve mqtt caps module
  priv/emqx.schema
  src/emqx_mqtt_caps.erl
  src/emqx_protocol.erl
  src/emqx_zone.erl
  test/emqx_mqtt_caps_SUITE.erl
Labels: Enhancement

#2767 Improve emqx_pmon module and add more test cases
  src/emqx_pmon.erl
  test/emqx_alarm_handler_SUITE.erl
  test/emqx_channel_SUITE.erl
  test/emqx_client_SUITE.erl
  test/emqx_flapping_SUITE.erl
  test/emqx_gc_SUITE.erl
  test/emqx_mod_rewrite_SUITE.erl
  test/emqx_pmon_SUITE.erl
  test/emqx_protocol_SUITE.erl
  test/emqx_shared_sub_SUITE.erl
  test/emqx_ws_channel_SUITE.erl
Labels: Enhancement

#2769 Add test cases for emqx_protocol module
  src/emqx_mod_subscription.erl
  src/emqx_mqtt_caps.erl
  src/emqx_protocol.erl
  src/emqx_session.erl
  test/emqx_protocol_SUITE.erl
Labels: Enhancement, Tests

#2773 Add more test cases for emqx_protocol module
  src/emqx_protocol.erl
  test/emqx_protocol_SUITE.erl
Labels: Tests

#2737 Remove the trap_exit process_flag
  src/emqx_channel.erl
Labels: Enhancement

#2783 Improve emqx_mqtt_props module and add test cases
  src/emqx_mqtt_props.erl
  test/emqx_mqtt_props_SUITE.erl
Labels: Tests

#2784 Add test cases for emqx_keepalive module
  src/emqx_keepalive.erl
  test/emqx_keepalive_SUITE.erl
Labels: Tests

#2805 Implement session takeover and resumption.
  src/emqx_channel.erl
  src/emqx_cm.erl
  src/emqx_connection.erl
  src/emqx_listeners.erl
  src/emqx_misc.erl
  src/emqx_mod_presence.erl
  src/emqx_oom.erl
  src/emqx_protocol.erl
  src/emqx_session.erl
  src/emqx_ws_connection.erl
  test/emqx_channel_SUITE.erl
  test/emqx_connection_SUITE.erl
  test/emqx_oom_SUITE.erl
  test/emqx_protocol_SUITE.erl
  test/emqx_ws_connection_SUITE.erl
Labels: Enhancement

#2807 Ensure stats timer
  src/emqx_channel.erl
  src/emqx_connection.erl
  src/emqx_ws_connection.erl
Labels: Enhancement

#2813 Improve the keepalive, connection, channel and session modules
  src/emqx_channel.erl
  src/emqx_cm.erl
  src/emqx_connection.erl
  src/emqx_keepalive.erl
  src/emqx_misc.erl
  src/emqx_packet.erl
  src/emqx_protocol.erl
  src/emqx_session.erl
  src/emqx_ws_connection.erl
  test/emqx_channel_SUITE.erl
  test/emqx_keepalive_SUITE.erl
  test/emqx_net_SUITE.erl
  test/emqx_packet_SUITE.erl
  test/emqx_protocol_SUITE.erl
  test/emqx_session_SUITE.erl
Labels: Enhancement

#2824 Improve emqx_ws_connection module
  src/emqx_ws_connection.erl
Labels: Enhancement

#2814 Monitor cluster partition event
  rebar.config
  src/emqx_sys_mon.erl
Labels: Enhancement

#2831 Improve session takeover
  src/emqx_channel.erl
  src/emqx_cm.erl
  src/emqx_connection.erl
  src/emqx_misc.erl
  src/emqx_session.erl
Labels: Enhancement

#2835 Handle the 'discard' cast.
  src/emqx_connection.erl
  src/emqx_ws_connection.erl
Labels: Enhancement

#2836 Fix case clause error
  src/emqx_channel.erl
  src/emqx_cm.erl
Labels: Enhancement
