Repository emqx/emqx, pull requests merged in 2020-11, with the labels that each got.

#3821 Feat/add inc message
  src/emqx.appup.src
  src/emqx_metrics.erl
Labels: Enhancement

#3823 feat(emqx_metrics): add new functions to count message received
  src/emqx.appup.src
  src/emqx_metrics.erl
Labels: BUG

#3841 Add readme Japanese translation
  README-CN.md
  README-JP.md
  README.md
Labels: Documentation
