Repository emqx/emqx, pull requests merged in 2020-10, with the labels that each got.

#3764 chore(types): add disconnected_at field in conninfo
  src/emqx_types.erl
Labels: Enhancement

#3766 chore(types): Add the disconnected_at field definition in conninfo
  src/emqx_types.erl
Labels: types

#3735 refactor(exproto): use grpcbox to replace erlport
  .gitignore
  apps/emqx_exproto/.gitignore
  apps/emqx_exproto/README.md
  apps/emqx_exproto/docs/design.md
  apps/emqx_exproto/docs/images/exproto-arch.jpg
  apps/emqx_exproto/docs/images/exproto-grpc-arch.jpg
  apps/emqx_exproto/docs/sdk-specification.md
  apps/emqx_exproto/example/Main.java
  apps/emqx_exproto/example/main.py
  apps/emqx_exproto/include/emqx_exproto.hrl
  apps/emqx_exproto/priv/emqx_exproto.schema
  apps/emqx_exproto/priv/protos/exproto.proto
  apps/emqx_exproto/rebar.config
  apps/emqx_exproto/sdk/README.md
  apps/emqx_exproto/src/emqx_exproto.app.src
  apps/emqx_exproto/src/emqx_exproto.erl
  apps/emqx_exproto/src/emqx_exproto_app.erl
  apps/emqx_exproto/src/emqx_exproto_channel.erl
  apps/emqx_exproto/src/emqx_exproto_conn.erl
  apps/emqx_exproto/src/emqx_exproto_driver_mngr.erl
  apps/emqx_exproto/src/emqx_exproto_gcli.erl
  apps/emqx_exproto/src/emqx_exproto_gsvr.erl
  apps/emqx_exproto/src/emqx_exproto_sup.erl
  apps/emqx_exproto/src/emqx_exproto_types.erl
  apps/emqx_exproto/test/emqx_exproto_SUITE.erl
  apps/emqx_exproto/test/emqx_exproto_echo_svr.erl
  etc/emqx_cloud.d/emqx_exproto.conf
Labels: Feature

#3732 Refactor(exhook): repalce erlport with grpcbox
  .gitignore
  apps/emqx_exhook/.gitignore
  apps/emqx_exhook/README.md
  apps/emqx_exhook/docs/design.md
  apps/emqx_exhook/include/emqx_exhook.hrl
  apps/emqx_exhook/priv/emqx_exhook.schema
  apps/emqx_exhook/priv/protos/exhook.proto
  apps/emqx_exhook/rebar.config
  apps/emqx_exhook/src/emqx_exhook.app.src
  apps/emqx_exhook/src/emqx_exhook.erl
  apps/emqx_exhook/src/emqx_exhook_app.erl
  apps/emqx_exhook/src/emqx_exhook_cli.erl
  apps/emqx_exhook/src/emqx_exhook_handler.erl
  apps/emqx_exhook/src/emqx_exhook_server.erl
  apps/emqx_exhook/src/emqx_exhook_sup.erl
  apps/emqx_exhook/test/emqx_exhook_SUITE.erl
  apps/emqx_exhook/test/emqx_exhook_demo_svr.erl
  apps/emqx_exhook/test/props/prop_exhook_hooks.erl
  apps/emqx_extension_hook/README.md
  apps/emqx_extension_hook/docs/design.md
  apps/emqx_extension_hook/docs/introduction.md
  apps/emqx_extension_hook/docs/sdk-specification.md
  apps/emqx_extension_hook/priv/emqx_extension_hook.schema
  apps/emqx_extension_hook/rebar.config
  apps/emqx_extension_hook/sdk/README.md
  apps/emqx_extension_hook/src/emqx_extension_hook.app.src
  apps/emqx_extension_hook/src/emqx_extension_hook_driver.erl
  apps/emqx_extension_hook/src/emqx_extension_hook_handler.erl
  apps/emqx_extension_hook/test/emqx_extension_hook_SUITE.erl
  apps/emqx_extension_hook/test/scripts/Main.java
  apps/emqx_extension_hook/test/scripts/main.py
  etc/emqx_cloud.d/emqx_exhook.conf
  etc/emqx_cloud.d/emqx_extension_hook.conf
  rebar.config
  rebar.lock
Labels: Enhancement, Refact

#3771 fix(ws): take ws_cookie to clientinfo
  src/emqx.appup.src
  src/emqx_channel.erl
  test/emqx_channel_SUITE.erl
Labels: BUG
