Repository emqx/emqx, pull requests merged in 2020-06, with the labels that each got.

#3505 fix(session): fix the race condition when opening sessions
  src/emqx_cm.erl
  test/emqx_cm_SUITE.erl
Labels: BUG

#3508 chore(deps): upgrade esockd to 5.6.2
  rebar.config
Labels: Enhancement

#3504 Correct the bad return value for emqx_modules:load/0
  src/emqx_modules.erl
Labels: BUG

#3493 Subscribe or unsubscribe via HTTP API skip ACL checking
  src/emqx_channel.erl
Labels: Enhancement

#3483 Add ensure/2 funcs to avoid needless logs
  src/emqx_metrics.erl
  src/emqx_reason_codes.erl
  src/emqx_types.erl
  test/emqx_metrics_SUITE.erl
Labels: Enhancement

#3521 fix(confs): delete `X-Forwarded-*` options for wss listener
  etc/emqx.conf
Labels: BUG

#3534 feature(properties): add properties in message header
  include/emqx.hrl
  include/emqx_mqtt.hrl
  src/emqx_alarm_handler.erl
  src/emqx_channel.erl
  src/emqx_frame.erl
  src/emqx_message.erl
  src/emqx_packet.erl
  src/emqx_session.erl
  src/emqx_types.erl
  test/emqx_channel_SUITE.erl
  test/emqx_frame_SUITE.erl
  test/emqx_listeners_SUITE.erl
  test/emqx_message_SUITE.erl
  test/emqx_packet_SUITE.erl
  test/emqx_session_SUITE.erl
  test/emqx_ws_connection_SUITE.erl
Labels: Feature

#3525 fix(enhanced_auth): fix bug when "conn_props = undefined"
  src/emqx_channel.erl
  test/emqx_channel_SUITE.erl
Labels: BUG

#3526 fix(enhanced_auth): fix bug when "conn_props = undefined"
  src/emqx_channel.erl
  test/emqx_channel_SUITE.erl
Labels: BUG

#3542 fix(json): convert a proplists to ejson instead of map
  src/emqx_json.erl
  test/props/prop_emqx_json.erl
Labels: Enhancement
