Repository emqx/emqx, pull requests merged in 2020-07, with the labels that each got.

#3570 refactor(channel): skip the ACL checking for inner subscribe
  src/emqx_channel.erl
  test/mqtt_protocol_v5_SUITE.erl
Labels: Enhancement

#3560 fix(props): fix the prop_emqx_sys results of judgment
  src/emqx_mod_delayed.erl
  test/props/prop_emqx_sys.erl
Labels: Enhancement

#3597 perf(emqx_vm): make emqx_vm:get_memory/0 more efficiency
  src/emqx_vm.erl
Labels: Enhancement

#3616 fix(emqx_channel)
  src/emqx_channel.erl
  test/emqx_channel_SUITE.erl
Labels: BUG

#3581 perf(emqx_vm): make emqx_vm:get_memory/0 more efficiency
  src/emqx_vm.erl
Labels: Enhancement

#3613 feat(ratelimit): refactor ratelimit
  etc/emqx.conf
  priv/emqx.schema
  rebar.config
  src/emqx_connection.erl
  src/emqx_limiter.erl
  src/emqx_ws_connection.erl
  src/emqx_zone.erl
  test/emqx_connection_SUITE.erl
  test/emqx_limiter_SUITE.erl
  test/emqx_ws_connection_SUITE.erl
  test/mqtt_protocol_v5_SUITE.erl
Labels: Feature

#3617 fix(emqx_channel): fix error for properties
  src/emqx_channel.erl
  test/emqx_channel_SUITE.erl
Labels: BUG
