Repository emqx/emqx, pull requests merged in 2020-12, with the labels that each got.

#3877 E422 to v430
  .gitignore
  etc/emqx.conf
  priv/emqx.schema
  src/emqx.appup.src
  src/emqx_alarm.erl
  src/emqx_channel.erl
  src/emqx_connection.erl
  src/emqx_frame.erl
  src/emqx_limiter.erl
  src/emqx_ws_connection.erl
  test/emqx_connection_SUITE.erl
  test/emqx_vm_SUITE.erl
  test/mqtt_protocol_v5_SUITE.erl
Labels: Enhancement

#3897 refactor(mqttsn): avoid saving anonymous functions
  apps/emqx_sn/src/emqx_sn_gateway.erl
  apps/emqx_sn/test/props/emqx_sn_proper_types.erl
  apps/emqx_sn/test/props/prop_emqx_sn_frame.erl
Labels: Refact

#3892 refactor(stomp): avoid anonymous functions
  apps/emqx_stomp/rebar.config
  apps/emqx_stomp/src/emqx_stomp_connection.erl
  apps/emqx_stomp/src/emqx_stomp_frame.erl
  apps/emqx_stomp/src/emqx_stomp_heartbeat.erl
  apps/emqx_stomp/src/emqx_stomp_protocol.erl
  apps/emqx_stomp/src/emqx_stomp_transaction.erl
  apps/emqx_stomp/test/emqx_stomp_SUITE.erl
  apps/emqx_stomp/test/emqx_stomp_heartbeat_SUITE.erl
Labels: Refact

#3831 fix(cm): fix the problem of registering a channel twice
  apps/emqx_coap/src/emqx_coap_mqtt_adapter.erl
  apps/emqx_exproto/src/emqx_exproto_conn.erl
  apps/emqx_lwm2m/src/emqx_lwm2m_protocol.erl
  apps/emqx_sn/src/emqx_sn_gateway.erl
  src/emqx_cm.erl
  src/emqx_connection.erl
  src/emqx_ws_connection.erl
  test/emqx_broker_SUITE.erl
  test/emqx_cm_SUITE.erl
  test/emqx_connection_SUITE.erl
  test/emqx_ws_connection_SUITE.erl
Labels: Enhancement

#3964 test(rule_engine): add update resource unit test case
  apps/emqx_rule_engine/src/emqx_rule_engine.erl
  apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
  apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
Labels: Enhancement

#3977 fix(rule_engine): fix resource update maybe failure
  apps/emqx_rule_engine/src/emqx_rule_engine.erl
Labels: BUG

#3974 fix(rule_engine): add resource reconnect check
  apps/emqx_rule_engine/include/rule_engine.hrl
  apps/emqx_rule_engine/src/emqx_rule_engine.erl
Labels: BUG
