Repository emqx/emqx, pull requests merged in 2021-01, with the labels that each got.

#3982 feat(auth_http): support for getting websocket cookies
  apps/emqx_auth_http/etc/emqx_auth_http.conf
  apps/emqx_auth_http/src/emqx_auth_http_cli.erl
  apps/emqx_auth_http/test/emqx_auth_http_SUITE.erl
  src/emqx_types.erl
Labels: Feature

#3940 improve(http): replace httpc with gun, improve performance and fix httpc unresponsiveness
  .github/workflows/.gitlint
  apps/emqx_auth_http/src/emqx_auth_http_app.erl
  apps/emqx_auth_http/src/emqx_auth_http_cli.erl
  apps/emqx_auth_http/test/emqx_auth_http_SUITE.erl
  apps/emqx_management/src/emqx_mgmt.erl
  apps/emqx_management/src/emqx_mgmt_api_data.erl
  apps/emqx_web_hook/etc/emqx_web_hook.conf
  apps/emqx_web_hook/include/emqx_web_hook.hrl
  apps/emqx_web_hook/priv/emqx_web_hook.schema
  apps/emqx_web_hook/rebar.config
  apps/emqx_web_hook/src/emqx_web_hook.app.src
  apps/emqx_web_hook/src/emqx_web_hook.erl
  apps/emqx_web_hook/src/emqx_web_hook_actions.erl
  apps/emqx_web_hook/src/emqx_web_hook_app.erl
Labels: Enhancement, Refact

#3991 fix(rule_engine): fix update problem and add cli
  apps/emqx_rule_engine/src/emqx_rule_engine.erl
  apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
  apps/emqx_rule_engine/src/emqx_rule_engine_cli.erl
  apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
Labels: Enhancement

#4001 fix(alarms): add duration field for alarms
  apps/emqx_management/src/emqx_mgmt.erl
Labels: Enhancement

#4012 fix(test): fix test cases
  .ci/apps_tests/docker-compose.yaml
  .ci/apps_tests/emqx_ldap/certs/cacert.pem
  .ci/apps_tests/emqx_ldap/certs/cert.pem
  .ci/apps_tests/emqx_ldap/certs/client-cert.pem
  .ci/apps_tests/emqx_ldap/certs/client-key.pem
  .ci/apps_tests/emqx_ldap/certs/key.pem
  .ci/apps_tests/emqx_ldap/schema/emqx.io.ldif
  .ci/apps_tests/emqx_ldap/schema/emqx.schema
  .ci/apps_tests/openldap/Dockerfile
  .ci/apps_tests/openldap/slapd.conf
  .ci/compatibility_tests/docker-compose-ldap.yaml
  .ci/compatibility_tests/docker-compose-pgsql-tls.yaml
  .ci/compatibility_tests/openldap/Dockerfile
  .ci/compatibility_tests/openldap/certs/cacert.pem
  .ci/compatibility_tests/openldap/certs/cert.pem
  .ci/compatibility_tests/openldap/certs/client-cert.pem
  .ci/compatibility_tests/openldap/certs/client-key.pem
  .ci/compatibility_tests/openldap/certs/key.pem
  .ci/compatibility_tests/openldap/schema/emqx.io.ldif
  .ci/compatibility_tests/openldap/schema/emqx.schema
  .ci/compatibility_tests/pgsql/Dockerfile
  .ci/compatibility_tests/pgsql/pg.conf
  .ci/compatibility_tests/pgsql/pg_hba.conf
  .github/workflows/run_cts_tests.yaml
  .github/workflows/run_test_cases.yaml
  apps/emqx_auth_mysql/test/emqx_auth_mysql_SUITE.erl
  apps/emqx_auth_pgsql/etc/emqx_auth_pgsql.conf
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE.erl
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/ca.pem
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/client-cert.pem
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/client-key.pem
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/pg.conf
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/postgresql.crt
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/postgresql.csr
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/postgresql.key
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/root.crt
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/root.srl
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/server-cert.pem
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/server-key.pem
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/server.crt
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE_data/server.key
Labels: Tests

#4016 fix(ekka): Upgrade to 0.7.6 to allow remsh
  rebar.config
Labels: BUG

#4015 fix(ekka): Upgrade to 0.8.0 to allow remsh
  rebar.config
Labels: BUG

#4018 perf(esockd): upgrade esockd to 5.8.0
  rebar.config
Labels: Enhancement

#4017 chore(deps): upgrade esockd to 5.7.5
  rebar.config
Labels: BUG

#4025 fix(test): add two way ssl test
  .github/workflows/run_cts_tests.yaml
  apps/emqx_auth_pgsql/etc/emqx_auth_pgsql.conf
  apps/emqx_auth_pgsql/priv/emqx_auth_pgsql.schema
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE.erl
Labels: SSL

#4042 fix(logs): print the correct username and clientid
  src/emqx_channel.erl
Labels: Refact

#4041 fix(exproto): fix the bad return type for auth
  apps/emqx_exproto/src/emqx_exproto_channel.erl
Labels: BUG

#4064 fix(rule-engine): resources may be deleted after update
  apps/emqx_rule_engine/src/emqx_rule_engine.erl
  apps/emqx_web_hook/src/emqx_web_hook_actions.erl
Labels: Enhancement

#4065 chore(redis): upgrade eredis_cluster to 0.6.4
  apps/emqx_auth_redis/rebar.config
Labels: BUG

#4057 fix emqx_vm allocator info otp 23 compatibility
  apps/emqx_recon/rebar.config
  rebar.config
  src/emqx_vm.erl
Labels: OTP-23

#4067 fix(webhook): fix bad https confs
  apps/emqx_web_hook/src/emqx_web_hook_app.erl
  apps/emqx_web_hook/test/emqx_web_hook_SUITE.erl
  apps/emqx_web_hook/test/http_server.erl
Labels: BUG

#4070 feat(rule-engine): change init resource to test resource
  apps/emqx_rule_engine/src/emqx_rule_engine.erl
  apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
  apps/emqx_rule_engine/src/emqx_rule_engine_cli.erl
Labels: BUG

#4086 fix(rule-engine): add format space
  apps/emqx_rule_engine/src/emqx_rule_engine.erl
Labels: types

#4092 fix(rule-engine): fix some format and rule engine problem
  apps/emqx_auth_mysql/test/emqx_auth_mysql_SUITE.erl
  apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE.erl
  apps/emqx_rule_engine/src/emqx_rule_actions.erl
  apps/emqx_rule_engine/src/emqx_rule_engine.erl
Labels: Enhancement

#4113 fix(rule-engine): reformat code style
  apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
  apps/emqx_rule_engine/src/emqx_rule_engine_cli.erl
  apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
Labels: Enhancement
