Repository emqx/emqx, pull requests merged in 2021-03, with the labels that each got.

#4253 Fix some issue during code review.
  apps/emqx_lwm2m/etc/emqx_lwm2m.conf
  apps/emqx_lwm2m/priv/emqx_lwm2m.schema
  apps/emqx_lwm2m/src/emqx_lwm2m_coap_server.erl
  apps/emqx_lwm2m/src/emqx_lwm2m_protocol.erl
  apps/emqx_rule_engine/src/emqx_rule_engine.erl
Labels: Enhancement

#4260 fix(mgmt): remove the useless match
  apps/emqx_management/src/emqx_mgmt.erl
Labels: BUG

#4301 feat(mgmt): add restart support
  apps/emqx_management/src/emqx_mgmt_api_listeners.erl
  apps/emqx_management/src/emqx_mgmt_cli.erl
  apps/emqx_management/src/emqx_mgmt_http.erl
  lib-ce/emqx_dashboard/src/emqx_dashboard.erl
Labels: Enhancement

#4298 feat(rule-engine): list rule support order by timestamp
  apps/emqx_rule_engine/include/rule_engine.hrl
  apps/emqx_rule_engine/src/emqx_rule_engine.erl
  apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
  apps/emqx_rule_engine/src/emqx_rule_engine_cli.erl
  apps/emqx_rule_engine/src/emqx_rule_registry.erl
  apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
Labels: Enhancement

#4364 fix(rule-engine): add 'undefined' type for create time
  apps/emqx_rule_engine/include/rule_engine.hrl
Labels: Enhancement

#4353 fix(backup): fix bridge-mqtt import problem
  apps/emqx_management/src/emqx_mgmt_data_backup.erl
Labels: BUG

#4413 refactor: improve the speed of hexstr and binary conversions
  apps/emqx_exhook/src/emqx_exhook_handler.erl
  apps/emqx_exproto/src/emqx_exproto_channel.erl
  apps/emqx_lwm2m/src/emqx_lwm2m_cmd_handler.erl
  apps/emqx_rule_engine/src/emqx_rule_funcs.erl
  src/emqx_guid.erl
  src/emqx_misc.erl
  src/emqx_tracer.erl
Labels: Benchmark, Enhancement

#4408 fix(import): add bridge_mqtt compatible <4.2.x
  apps/emqx_management/include/emqx_mgmt.hrl
  apps/emqx_management/src/emqx_mgmt_data_backup.erl
Labels: Enhancement

#4417 fix(import): fix import error
  apps/emqx_management/src/emqx_mgmt_data_backup.erl
Labels: Enhancement

#4425 fix(ping): deny pingreq when mqtt not connected
  src/emqx_connection.erl
  src/emqx_ws_connection.erl
  test/emqx_connection_SUITE.erl
Labels: BUG

#4438 fix(mgmt): expose 2 functions to ce
  apps/emqx_management/src/emqx_mgmt_data_backup.erl
Labels: Enhancement

#4444 fix(channel): fix `keep-alive` problem
  src/emqx_channel.erl
Labels: BUG
