Repository emqx/emqx, pull requests merged in 2021-04, with the labels that each got.

#4510 chore(dashboard): upgrade front-page version
  Makefile
Labels: Enhancement

#4486 chore(extra-plugin): statement plugin tag
  lib-extra/README.md
Labels: Documentation

#4503 fix(http api): fix badarg caused by acl cache api
  apps/emqx_management/src/emqx_mgmt_api_acl.erl
Labels: BUG

#4481 test(mgmt): add data import tests
  apps/emqx_bridge_mqtt/test/emqx_bridge_worker_SUITE.erl
  apps/emqx_management/src/emqx_mgmt_data_backup.erl
  apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE.erl
  apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE_data/409.json
  apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE_data/415.json
  apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE_data/420.json
  apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE_data/430.json
  apps/emqx_management/test/emqx_mgmt_api_SUITE.erl
  apps/emqx_management/test/emqx_webhook_data_export_import_SUITE.erl
  apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/409.json
  apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/415.json
  apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/422.json
  apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/423.json
  apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/425.json
  apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/430.json
  apps/emqx_web_hook/test/emqx_web_hook_SUITE.erl
Labels: Tests

#4500 fix(lwm2m): decode/encode data as signed integer
  apps/emqx_lwm2m/src/emqx_lwm2m_message.erl
Labels: BUG

#4549 test(mgmt): remove unused ct log
  apps/emqx_management/src/emqx_mgmt_data_backup.erl
Labels: Tests

#4526 fix(emqx_bridge_mqtt): fix retry_inflight
  apps/emqx_bridge_mqtt/src/emqx_bridge_worker.erl
  apps/emqx_bridge_mqtt/test/emqx_bridge_stub_conn.erl
  apps/emqx_bridge_mqtt/test/emqx_bridge_worker_SUITE.erl
Labels: BUG

#4527 feat(log): rfc3339 date-time format in logs
  etc/emqx.conf
  priv/emqx.schema
  src/emqx_logger_formatter.erl
  test/emqx_logger_formatter_SUITE.erl
Labels: Feature

#4558 feat(emqx_ws_connection): #4184 check http header to know real IP/port
  etc/emqx.conf
  priv/emqx.schema
  src/emqx_ws_connection.erl
  test/emqx_ws_connection_SUITE.erl
Labels: Feature

#4596 test(mgmt): remove macro switch
  apps/emqx_management/src/emqx_mgmt_data_backup.erl
  apps/emqx_management/test/test_utils.erl
Labels: Tests

#4678 fix(exhook): allow certificate options absent
  apps/emqx_exhook/priv/emqx_exhook.schema
Labels: BUG

#4684 feat(exhook): add ssl cert info to ClientInfo
  apps/emqx_exhook/priv/protos/exhook.proto
  apps/emqx_exhook/src/emqx_exhook_handler.erl
  apps/emqx_exhook/test/props/prop_exhook_hooks.erl
Labels: Feature

#4706 fix(deps): fix function clause at apply_new_config
  apps/emqx_management/src/emqx_mgmt_data_backup.erl
Labels: BUG
