Repository emqx/emqx, pull requests merged in 2021-02, with the labels that each got.

#4120 fix(rule-engine): add error return to frontend
  apps/emqx_rule_engine/src/emqx_rule_engine.erl
  apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
  apps/emqx_web_hook/src/emqx_web_hook_actions.erl
Labels: BUG

#4146 fix(rule-engine): remove plugin_template
  apps/emqx_plugin_template/.gitignore
  apps/emqx_plugin_template/README.md
  apps/emqx_plugin_template/TODO
  apps/emqx_plugin_template/etc/emqx_plugin_template.config
  apps/emqx_plugin_template/rebar.config
  apps/emqx_plugin_template/src/emqx_cli_demo.erl
  apps/emqx_plugin_template/src/emqx_plugin_template.app.src
  apps/emqx_plugin_template/src/emqx_plugin_template.erl
  apps/emqx_plugin_template/src/emqx_plugin_template_app.erl
  apps/emqx_plugin_template/src/emqx_plugin_template_sup.erl
  apps/emqx_plugin_template/test/emqx_plugin_template_SUITE.erl
  rebar.config.erl
  sync-apps.sh
Labels: Enhancement

#4137 fix(rulesql): proc_sql_param_str incorrect with apostrophes #4135
  apps/emqx_rule_engine/src/emqx_rule_utils.erl
  apps/emqx_rule_engine/test/emqx_rule_utils_SUITE.erl
Labels: BUG

#4124 fix(mgmt): fix client formating crash
  lib-opensource/emqx_management/src/emqx_mgmt.erl
  lib-opensource/emqx_management/src/emqx_mgmt_api_clients.erl
Labels: BUG

#4213 chore(jwt): clearer explanation for verify_claims
  apps/emqx_auth_jwt/etc/emqx_auth_jwt.conf
Labels: Documentation
